/**
 * Command Center - Mock Data
 * 실제 GitHub Actions 연동 전 데모용 한국어 뉴스 데이터
 */

import type { NewsItem, AIAnalysis, SystemStatus, AccountInfo } from './types';

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: '비트코인 ETF 순유입 3일 연속 증가, 기관 투자자 매수세 강화',
    summary: '블랙록과 피델리티의 비트코인 현물 ETF가 3일 연속 순유입을 기록하며 기관 투자자들의 매수세가 강화되고 있다. 총 유입액은 약 8억 달러에 달한다.',
    fullAnalysis: '블랙록의 IBIT와 피델리티의 FBTC가 주도하는 비트코인 현물 ETF 시장이 3일 연속 순유입을 기록했다. 이는 기관 투자자들의 비트코인에 대한 신뢰가 회복되고 있음을 시사한다. 특히 블랙록의 IBIT는 단일 일 기준 4.5억 달러의 유입을 기록하며 시장의 주목을 받았다. 전문가들은 이러한 추세가 비트코인 가격의 상승 모멘텀을 제공할 것으로 전망하고 있다.',
    category: '암호화폐',
    priority: 'high',
    marketImpact: 'very_bullish',
    source: 'Bloomberg',
    sourceHandle: '@bloomingbit_io',
    sourceUrl: 'https://x.com/bloomingbit_io',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    relatedAccounts: ['@WuBlockchain', '@zoomerfied'],
    tags: ['비트코인', 'ETF', '기관투자'],
    impactScore: 92,
  },
  {
    id: '2',
    title: '트럼프, 새로운 관세 정책 발표 예정 - 중국 반도체 수출 규제 강화',
    summary: '트럼프 대통령이 중국산 반도체에 대한 추가 관세를 발표할 예정이다. 이는 미중 기술 패권 경쟁의 새로운 국면을 예고한다.',
    fullAnalysis: '트럼프 대통령이 중국산 반도체 및 관련 부품에 대해 25%의 추가 관세를 부과할 계획이라고 복수의 소식통이 전했다. 이 조치는 미국의 기술 공급망 안보를 강화하려는 전략의 일환으로, 특히 AI 칩과 첨단 반도체에 초점을 맞추고 있다. 시장 전문가들은 이 정책이 글로벌 반도체 공급망에 상당한 영향을 미칠 것으로 예상하고 있으며, 한국과 대만의 반도체 기업들도 간접적인 영향을 받을 수 있다.',
    category: '트럼프',
    priority: 'critical',
    marketImpact: 'bearish',
    source: 'Mario Nawfal',
    sourceHandle: '@MarioNawfal',
    sourceUrl: 'https://x.com/MarioNawfal',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    relatedAccounts: ['@dons_korea', '@martypartymusic'],
    tags: ['트럼프', '관세', '반도체', '미중갈등'],
    impactScore: 95,
  },
  {
    id: '3',
    title: '러시아-우크라이나 휴전 협상 진전, 에너지 시장 반응 주목',
    summary: '러시아와 우크라이나 간 휴전 협상이 진전을 보이고 있으며, 이에 따른 에너지 시장의 반응이 주목받고 있다.',
    fullAnalysis: '러시아와 우크라이나 간의 휴전 협상이 의미 있는 진전을 보이고 있다는 보도가 나왔다. 양측은 곡물 수출 통로 확보와 포로 교환에 대해 잠정 합의에 도달한 것으로 알려졌다. 이 소식에 유럽 천연가스 선물 가격이 5% 이상 하락했으며, 원유 시장도 하방 압력을 받고 있다. 지정학적 리스크 완화는 글로벌 인플레이션 압력 완화에도 기여할 것으로 전망된다.',
    category: '지정학',
    priority: 'high',
    marketImpact: 'bullish',
    source: 'Zoomer',
    sourceHandle: '@zoomerfied',
    sourceUrl: 'https://x.com/zoomerfied',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    relatedAccounts: ['@MarioNawfal'],
    tags: ['러시아', '우크라이나', '에너지', '휴전'],
    impactScore: 88,
  },
  {
    id: '4',
    title: '연준 의사록 공개 - 금리 인하 시기 논의 본격화',
    summary: '연준 의사록에서 다수의 위원들이 올해 하반기 금리 인하 가능성을 논의한 것으로 확인되었다.',
    fullAnalysis: '최근 공개된 연방준비제도(Fed) 의사록에 따르면, 다수의 위원들이 인플레이션 데이터가 지속적으로 개선될 경우 올해 하반기 금리 인하를 시작할 수 있다는 의견을 제시했다. 특히 일부 위원들은 노동 시장의 냉각 조짐을 근거로 보다 적극적인 완화 정책을 주장했다. 이 소식에 미국 국채 수익률이 하락하고, 주식 시장은 상승세를 보였다.',
    category: '경제',
    priority: 'high',
    marketImpact: 'bullish',
    source: 'Wu Blockchain',
    sourceHandle: '@WuBlockchain',
    sourceUrl: 'https://x.com/WuBlockchain',
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    relatedAccounts: ['@bloomingbit_io'],
    tags: ['연준', '금리', '통화정책'],
    impactScore: 85,
  },
  {
    id: '5',
    title: '이더리움 레이어2 TVL 사상 최고치 갱신',
    summary: 'Arbitrum과 Optimism을 중심으로 이더리움 레이어2 솔루션의 총 예치금(TVL)이 사상 최고치를 기록했다.',
    fullAnalysis: '이더리움 레이어2 생태계의 총 예치금(TVL)이 500억 달러를 돌파하며 사상 최고치를 경신했다. Arbitrum이 전체의 40%를 차지하며 선두를 유지하고 있으며, Base와 Optimism이 그 뒤를 잇고 있다. 이는 이더리움 확장성 솔루션에 대한 시장의 신뢰가 높아지고 있음을 보여준다. DeFi 프로토콜들의 레이어2 이전이 가속화되면서 가스비 절감과 처리 속도 향상이 실현되고 있다.',
    category: '암호화폐',
    priority: 'medium',
    marketImpact: 'bullish',
    source: 'Dons Korea',
    sourceHandle: '@dons_korea',
    sourceUrl: 'https://x.com/dons_korea',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    relatedAccounts: ['@WuBlockchain', '@zoomerfied'],
    tags: ['이더리움', '레이어2', 'DeFi', 'TVL'],
    impactScore: 72,
  },
  {
    id: '6',
    title: 'SEC, 새로운 암호화폐 규제 프레임워크 초안 발표',
    summary: 'SEC가 암호화폐 거래소와 스테이블코인에 대한 새로운 규제 프레임워크 초안을 공개했다.',
    fullAnalysis: '미국 증권거래위원회(SEC)가 암호화폐 산업에 대한 포괄적인 규제 프레임워크 초안을 발표했다. 이 프레임워크는 암호화폐 거래소의 등록 요건, 스테이블코인 발행사의 준비금 요건, 그리고 DeFi 프로토콜에 대한 규제 가이드라인을 포함하고 있다. 업계에서는 이 프레임워크가 규제 불확실성을 해소하는 데 기여할 것으로 기대하면서도, 일부 조항이 지나치게 엄격하다는 우려도 제기하고 있다.',
    category: '규제',
    priority: 'high',
    marketImpact: 'neutral',
    source: 'Marty Party',
    sourceHandle: '@martypartymusic',
    sourceUrl: 'https://x.com/martypartymusic',
    timestamp: new Date(Date.now() - 150 * 60000).toISOString(),
    relatedAccounts: ['@dons_korea', '@bloomingbit_io'],
    tags: ['SEC', '규제', '스테이블코인', 'DeFi'],
    impactScore: 80,
  },
  {
    id: '7',
    title: '일본 엔화 급락, 달러/엔 155선 돌파 - BOJ 개입 가능성',
    summary: '일본 엔화가 달러 대비 155선을 돌파하며 급락했다. 일본은행(BOJ)의 시장 개입 가능성이 높아지고 있다.',
    fullAnalysis: '일본 엔화가 달러 대비 155선을 돌파하며 34년 만의 최저치를 기록했다. 미일 금리차 확대와 일본의 무역적자 지속이 엔화 약세의 주요 원인으로 지목되고 있다. 일본 재무성은 "과도한 환율 변동에 대해 적절한 조치를 취할 것"이라고 경고했으며, 시장에서는 BOJ의 직접 개입 가능성을 주시하고 있다.',
    category: '경제',
    priority: 'medium',
    marketImpact: 'bearish',
    source: 'Bloomberg',
    sourceHandle: '@bloomingbit_io',
    sourceUrl: 'https://x.com/bloomingbit_io',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
    relatedAccounts: ['@WuBlockchain'],
    tags: ['엔화', '환율', 'BOJ', '달러'],
    impactScore: 68,
  },
  {
    id: '8',
    title: '솔라나 네트워크 업그레이드 완료 - 처리 속도 2배 향상',
    summary: '솔라나가 Firedancer 업그레이드를 성공적으로 완료하며 네트워크 처리 속도가 2배 이상 향상되었다.',
    fullAnalysis: '솔라나 네트워크가 대규모 업그레이드인 Firedancer를 성공적으로 완료했다. 이번 업그레이드로 네트워크의 초당 트랜잭션 처리량이 기존 대비 2배 이상 향상되었으며, 네트워크 안정성도 크게 개선되었다. Jump Crypto가 개발한 Firedancer 클라이언트는 기존 Solana Labs 클라이언트와 병행 운영되며, 네트워크의 탈중앙화와 복원력을 강화한다.',
    category: '암호화폐',
    priority: 'medium',
    marketImpact: 'bullish',
    source: 'Wu Blockchain',
    sourceHandle: '@WuBlockchain',
    sourceUrl: 'https://x.com/WuBlockchain',
    timestamp: new Date(Date.now() - 200 * 60000).toISOString(),
    relatedAccounts: ['@dons_korea'],
    tags: ['솔라나', 'Firedancer', '업그레이드'],
    impactScore: 65,
  },
];

export const mockAIAnalyses: AIAnalysis[] = [
  {
    id: 'a1',
    title: '시장 종합 분석: 매크로 환경과 암호화폐 시장 전망',
    content: '현재 글로벌 매크로 환경은 암호화폐 시장에 복합적인 영향을 미치고 있습니다. 연준의 금리 인하 기대감이 높아지면서 위험자산 선호 심리가 강화되고 있으나, 미중 무역 갈등과 지정학적 리스크가 상존하고 있습니다.\n\n비트코인 ETF의 지속적인 순유입은 기관 투자자들의 참여가 확대되고 있음을 보여주며, 이는 시장의 성숙도가 높아지고 있다는 긍정적 신호입니다. 다만, 트럼프 행정부의 관세 정책 불확실성이 단기적으로 시장 변동성을 높일 수 있습니다.\n\n종합적으로, 중장기 전망은 긍정적이나 단기적으로는 변동성 확대에 대비할 필요가 있습니다.',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    category: '암호화폐',
    sentiment: 'bullish',
    keyInsights: [
      '비트코인 ETF 3일 연속 순유입 - 기관 매수세 강화',
      '연준 금리 인하 기대감 상승 - 위험자산 선호',
      '미중 관세 갈등 - 단기 변동성 요인',
      '이더리움 L2 TVL 사상 최고 - 생태계 확장',
    ],
    riskLevel: 'medium',
  },
  {
    id: 'a2',
    title: '지정학 리스크 분석: 러시아-우크라이나 및 미중 관계',
    content: '러시아-우크라이나 휴전 협상 진전은 에너지 시장과 글로벌 인플레이션에 긍정적 영향을 미칠 수 있습니다. 반면, 트럼프 행정부의 대중국 반도체 관세 강화는 기술 섹터에 새로운 불확실성을 가져올 수 있습니다.\n\n이 두 가지 지정학적 이벤트는 상반된 방향으로 시장에 영향을 미치고 있으며, 투자자들은 포트폴리오 다각화를 통해 리스크를 관리할 필요가 있습니다.',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    category: '지정학',
    sentiment: 'neutral',
    keyInsights: [
      '러시아-우크라이나 휴전 협상 진전 - 에너지 가격 하락',
      '미중 반도체 관세 강화 예고 - 기술주 압박',
      '엔화 급락으로 아시아 통화 불안 확대',
    ],
    riskLevel: 'high',
  },
];

export const mockSystemStatus: SystemStatus = {
  lastUpdate: new Date(Date.now() - 15 * 60000).toISOString(),
  nextUpdate: new Date(Date.now() + 225 * 60000).toISOString(),
  totalAccounts: 60,
  activeAccounts: 58,
  tweetsCollected: 147,
  aiAnalysisCount: 12,
  systemHealth: 'operational',
  uptime: '99.7%',
};

export const mockAccounts: AccountInfo[] = [
  { handle: '@dons_korea', name: 'Dons Korea', category: '암호화폐', isPriority: true, lastTweet: new Date(Date.now() - 30 * 60000).toISOString(), tweetCount: 12 },
  { handle: '@bloomingbit_io', name: 'Blooming Bit', category: '암호화폐', isPriority: true, lastTweet: new Date(Date.now() - 45 * 60000).toISOString(), tweetCount: 18 },
  { handle: '@WuBlockchain', name: 'Wu Blockchain', category: '암호화폐', isPriority: true, lastTweet: new Date(Date.now() - 60 * 60000).toISOString(), tweetCount: 15 },
  { handle: '@zoomerfied', name: 'Zoomer', category: '지정학', isPriority: true, lastTweet: new Date(Date.now() - 90 * 60000).toISOString(), tweetCount: 8 },
  { handle: '@MarioNawfal', name: 'Mario Nawfal', category: '지정학', isPriority: true, lastTweet: new Date(Date.now() - 120 * 60000).toISOString(), tweetCount: 22 },
  { handle: '@martypartymusic', name: 'Marty Party', category: '암호화폐', isPriority: true, lastTweet: new Date(Date.now() - 150 * 60000).toISOString(), tweetCount: 10 },
  { handle: '@coindesk', name: 'CoinDesk', category: '암호화폐', isPriority: false, lastTweet: new Date(Date.now() - 20 * 60000).toISOString(), tweetCount: 25 },
  { handle: '@caboringcrypto', name: 'Boring Crypto', category: '암호화폐', isPriority: false, lastTweet: new Date(Date.now() - 35 * 60000).toISOString(), tweetCount: 7 },
  { handle: '@Reuters', name: 'Reuters', category: '지정학', isPriority: false, lastTweet: new Date(Date.now() - 40 * 60000).toISOString(), tweetCount: 30 },
  { handle: '@AP', name: 'AP News', category: '지정학', isPriority: false, lastTweet: new Date(Date.now() - 55 * 60000).toISOString(), tweetCount: 28 },
];
